// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOePy4gDzV765_MTcscHFfXk3wuELeKc',
    appId: '1:201999207325:android:18d3dde5ca8f28dfd7bd74',
    messagingSenderId: '201999207325',
    projectId: 'pharmacy-app-1449f',
    storageBucket: 'pharmacy-app-1449f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8dh5TRJ-DzC957i2qiMNnQLcD0L9lJlA',
    appId: '1:201999207325:ios:afdb452dd6049f2ad7bd74',
    messagingSenderId: '201999207325',
    projectId: 'pharmacy-app-1449f',
    storageBucket: 'pharmacy-app-1449f.firebasestorage.app',
    iosBundleId: 'com.rasel.habittracker.habitTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCG3nnb2yHCPwepy9xHm1Og6s9W10K5W8',
    appId: '1:201999207325:web:486e1be2c90aa4fed7bd74',
    messagingSenderId: '201999207325',
    projectId: 'pharmacy-app-1449f',
    authDomain: 'pharmacy-app-1449f.firebaseapp.com',
    storageBucket: 'pharmacy-app-1449f.firebasestorage.app',
    measurementId: 'G-JDGY6SG6BV',
  );

}